# Generated by Django 3.0.2 on 2020-03-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
