# Generated by Django 3.0.2 on 2020-04-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0003_auto_20200331_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
