# Generated by Django 3.0.5 on 2020-04-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0006_auto_20200403_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='items',
            new_name='labels',
        ),
    ]
