# Generated by Django 3.0.2 on 2020-04-05 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mellonsforsale', '0007_auto_20200403_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='interested',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
