# Generated by Django 3.0.5 on 2020-04-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0008_item_interested'),
        ('mellonsforsale', '0008_auto_20200403_2243'),
    ]

    operations = [
    ]
