# Generated by Django 3.0.5 on 2020-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0009_merge_20200407_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='interested',
            field=models.ManyToManyField(to='mellonsforsale.Profile'),
        ),
    ]
