# Generated by Django 3.0.5 on 2020-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0010_auto_20200419_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.TextField(default='PA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='street',
            field=models.TextField(default='5000 Forbes Avenue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='zip_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
