# Generated by Django 3.0.5 on 2020-07-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mellonsforsale', '0011_auto_20200705_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
